<!DOCTYPE html>
<html lang="en">
    <head>
	<link rel="stylesheet" type="text/css" href="http://getbootstrap.com/dist/css/bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="main.css" />
    </head>
    <body>
	<a class="sr-only" href="#content"> … </a>
	<header class="navbar navbar-inverse navbar-fixed-top laminasa1-nav" role="banner">
	    <div class="container">
		<div class="navbar-header">
		    <a href="/admin" class="navbar-brand">
			<img src="/api-tools/img/laminasa1-logo.png">
		    </a>
		    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".laminasa1-navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		    </button>


		</div>
		<nav class="collapse navbar-collapse laminasa1-navbar-collapse" role="navigation">
		    <ul class="nav navbar-nav">
			<li class="laminasa1-nav-dashboard active">
			    <a href="#">Dashboard</a>
			</li>
			<li>
			    <a href="/apidoc">API Doc</a>
			</li>
		    </ul>
		</nav>


	    </div>
	</header>

	<?= $this->content ?>

    </body>
</html>
