<?php
$version = 'dist';
$path    = __DIR__ . '/../asset/' . $version . '/api-tools-admin/index.html';
$apiBase = $this->url('api-tools/api/module');
$apiBase = substr($apiBase, 0, strrpos($apiBase, '/'));
$docUri  = (class_exists('Laminas\ApiTools\Documentation\Module')) ? $this->url('api-tools/documentation') : '';

$basePath = $this->serverUrl(rtrim($this->basePath(), '/') . '/api-tools-admin');

$html = file_get_contents($path);
$html = str_replace('%BASE_HREF%', $basePath, $html);
$html = str_replace('%API_BASE%', $apiBase, $html);
$html = str_replace('%DOC_URI%', $docUri, $html);
echo $html;
